apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: air-quality-pvc
  namespace: air-quality-monitor
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
